# Extension Metadata
name=Load Big GeoJSON Extension
version=1.0.0
author=Gabriel Ascui
description=Streaming importer for large GeoJSON(.gz) files in QuPath 0.6.x; supports Polygon/MultiPolygon/Point/Line geometries.
mainClass=qupath.ext.load_obj_chunk.LoadBigGeoJSON

# Menu items
